package edu.psu.axs7326.american_buddy.db;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName="slangs")
public class Slang {

    // Note that if id == 0, and this is inserted, an id will be autogenerated
    public Slang(int id, String title, String slang, String english_meaning, boolean liked) {
        this.id = id;
        this.title = title;
        this.slang = slang;
        this.english_meaning = english_meaning;
        this.liked = liked;
    }

    // Assign 0 to id to have it be auto generated
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "rowid")
    public int id;

    @ColumnInfo(name = "title")
    public String title;

    @ColumnInfo(name = "slang")
    public String slang;

    @ColumnInfo(name = "english_meaning")
    public String english_meaning;

    @ColumnInfo(name = "liked")
    public boolean liked;
}
